tap "hashicorp/tap"
tap "homebrew/bundle"
brew "asdf"
brew "python@3.12"
brew "glib"
brew "docker"
brew "docker-compose"
brew "go"
brew "graphviz"
brew "helm"
brew "inframap"
brew "jq"
brew "kind"
brew "libimobiledevice"
brew "libpq"
brew "libslirp"
brew "libzip"
brew "qemu"
brew "lima"
brew "mas"
brew "maven"
brew "minikube"
brew "openconnect"
brew "poetry"
brew "pure"
brew "python@3.11"
brew "rclone"
brew "stern"
brew "tesseract"
brew "tesseract-lang"
brew "vpn-slice"
brew "zsh-autosuggestions"
brew "zsh-completions"
brew "hashicorp/tap/terraform"
cask "android-platform-tools"
cask "android-studio"
cask "chrome-remote-desktop-host"
cask "db-browser-for-sqlite"
cask "dropbox"
cask "google-chrome"
cask "google-cloud-sdk"
cask "google-drive"
cask "google-japanese-ime"
cask "iterm2"
cask "lens"
cask "microsoft-azure-storage-explorer"
cask "microsoft-edge"
cask "microsoft-remote-desktop"
cask "pgadmin4"
cask "postman"
cask "scroll-reverser"
cask "tableau-public"
cask "visual-studio-code"
cask "wireshark"
cask "xbar"
cask "zoom"
mas "Bitwarden", id: 1352778147
mas "Display Menu", id: 549083868
mas "Keynote", id: 409183694
mas "Kindle", id: 302584613
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Sleep Control Center", id: 946798523
mas "Xcode", id: 497799835
vscode "arjun.swagger-viewer"
vscode "bierner.markdown-mermaid"
vscode "hediet.vscode-drawio"
vscode "jebbs.plantuml"
vscode "leetcode.vscode-leetcode"
vscode "mitchdenny.ecdc"
vscode "ms-ceintl.vscode-language-pack-ja"
vscode "ms-python.debugpy"
vscode "ms-python.isort"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.jupyter-keymap"
vscode "ms-toolsai.jupyter-renderers"
vscode "ms-toolsai.vscode-jupyter-cell-tags"
vscode "ms-toolsai.vscode-jupyter-slideshow"
vscode "ms-vscode.cpptools"
vscode "ms-vscode.vscode-serial-monitor"
vscode "redhat.vscode-yaml"
vscode "vsciot-vscode.vscode-arduino"
