#!/bin/zsh

LIMA_INSTANCE="default"
SOCKET_PATH="$HOME/.lima/$LIMA_INSTANCE/sock/docker.sock"
ENV_FILE="$HOME/.docker-host-env"

case "$1" in
  start)
    limactl start "$LIMA_INSTANCE" || exit 1
    echo "export DOCKER_HOST=unix://$SOCKET_PATH" > "$ENV_FILE"
    echo "Lima started. DOCKER_HOST set in future terminals."
    echo "In this terminal, run 'source $ENV_FILE' to set DOCKER_HOST now."
    ;;
  stop)
    limactl stop "$LIMA_INSTANCE" || exit 1
    rm -f "$ENV_FILE"
    echo "Lima stopped. DOCKER_HOST will be unset in future terminals."
    echo "In this terminal, run 'unset DOCKER_HOST' to unset it now."
    ;;
  shell)
    export DOCKER_HOST="unix://$SOCKET_PATH"
    exec $SHELL
    ;;
  *)
    echo "Usage: $0 {start|stop|shell}"
    exit 1
    ;;
esac
