#!/usr/bin/env python

import sys
import math
import xml.etree.ElementTree as ET

tree = ET.parse(sys.argv[1])
root = tree.getroot()

prev_lat = None
prev_lon = None
meter_per_second = 1.50  # 80m/1分 -> 1.3333

print('<?xml version="1.0" encoding="UTF-8"?>')
print('<gpx version="1.1" creator="GPX Editor and Viewer 0.14" xmlns="http://www.topografix.com/GPX/1/1">')

#for wpt in root.findall('.//{http://www.topografix.com/GPX/1/1}wpt'):
for wpt in root.findall('.//{http://www.topografix.com/GPX/1/1}trkpt'):
  current_lat = float(wpt.get('lat'))
  current_lon = float(wpt.get('lon'))
  if prev_lat:
    r = math.sqrt(((40009/360*(current_lat - prev_lat))**2)
                   +((40075/360*(current_lon - prev_lon))**2))*1000
    #rad = math.atan((current_lat - prev_lat)/(current_lon - prev_lon))
    split_num = int(r // meter_per_second)
    delta_lat = 0
    delta_lon = 0
    for i in range(split_num-1):
      delta_lat += (current_lat - prev_lat) / split_num
      delta_lon += (current_lon - prev_lon) / split_num
      print('  <wpt lat="' + str(prev_lat+delta_lat) + '" '
                 + 'lon="' + str(prev_lon+delta_lon) + '" />')

    #print("r=",r," split_num=",split_num)
    #print("rad=",rad," degree=",math.degrees(rad))
    #print("x=",r*math.cos(rad),"y=",r*math.sin(rad))

  #print("<wpt lat=\"" + str(current_lat) + "\" "
  #         + "lon=\"" + str(current_lon) + "\" />")
  print('<wpt lat="' + str(current_lat) + '" '
           + 'lon="' + str(current_lon) + '" />')

  prev_lat = current_lat
  prev_lon = current_lon

print('</gpx>')
