#!/bin/zsh

#exec ~/Library/Android/sdk/emulator/emulator -avd Pixel_4_API_30 -netdelay none -netspeed full -http-proxy http://10.0.2.2:8080 >/dev/null 2>&1 &
exec ~/Library/Android/sdk/emulator/emulator -avd Pixel_4_API_30 -netdelay none -netspeed full >/dev/null 2>&1 &
