name: Ubuntu

on: [push]

jobs:
  ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: Setup
        run: |
          DEBUG=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/myako10s/dotfiles/HEAD/install.sh)"
