name: Ubuntu

on: [push]

jobs:
  ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: Setup
        run: |
          DEBUG=1 /bin/bash -c "$(curl -fsSL https://myako10s.github.io/dotfiles/install.sh)"
